import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import client from './client.json';

function buildSidebar(): SidebarsConfig {
  const items: any[] = [
    {type: 'doc', id: 'intro', label: 'Overview'},
  ];

  // Phase categories from client.json
  if (client.phases && client.phases.length > 0) {
    for (const phase of client.phases) {
      items.push({
        type: 'category',
        label: `${phase.id}. ${phase.label}`,
        items: [{type: 'autogenerated', dirName: `${phase.id}-${phase.slug}`}],
        link: {type: 'generated-index'},
        collapsed: true,
      });
    }
  }

  // Cohort section for coaching engagements
  if (['cohort-coaching', 'individual-coaching'].includes(client.engagementType)) {
    items.push({
      type: 'category',
      label: 'Cohort',
      items: [{type: 'autogenerated', dirName: 'cohort'}],
      link: {type: 'generated-index'},
      collapsed: false,
    });
  }

  // Tools & Assessments (always present)
  items.push({
    type: 'category',
    label: 'Tools & Assessments',
    items: [{type: 'autogenerated', dirName: 'tools-assessments'}],
    link: {type: 'generated-index'},
    collapsed: true,
  });

  return {defaultSidebar: items};
}

export default buildSidebar();
