import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import clientConfig from './client.json';

const isCoaching =
  clientConfig.engagementType === 'cohort-coaching' ||
  clientConfig.engagementType === 'individual-coaching';

const phaseItems = clientConfig.phases.map((phase) => ({
  type: 'category' as const,
  label: `${phase.label}`,
  link: {type: 'generated-index' as const},
  items: [
    {
      type: 'autogenerated' as const,
      dirName: `${phase.id}-${phase.slug}`,
    },
  ],
}));

const sidebars: SidebarsConfig = {
  engagementSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    ...phaseItems,
    ...(isCoaching
      ? [
          {
            type: 'category' as const,
            label: 'Cohort',
            link: {type: 'generated-index' as const},
            items: [
              {
                type: 'autogenerated' as const,
                dirName: 'cohort',
              },
            ],
          },
        ]
      : []),
    {
      type: 'category' as const,
      label: 'Tools & Assessments',
      link: {type: 'generated-index' as const},
      items: [
        {
          type: 'autogenerated' as const,
          dirName: 'tools-assessments',
        },
      ],
    },
  ],
};

export default sidebars;
